name: CI

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-22.04.01
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, 3.10]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -f requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
